name: lint-and-unit-tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - id: browser
      uses: fippo/multirunner-action@0.2
    - run: ${{steps.browser.outputs.path}} --version
